language: java
dist: bionic
sudo: false

# Get latest install-jdk.sh script
before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

matrix:
  include:
    - env: JDK='OpenJDK 10'
      install: . ./install-jdk.sh -F 10 -L GPL

script:
  - mvn clean package
